// Schema Generators - Export to different formats
import { ParsedSchema, Table, Column, Relationship } from '../sql-parser';

// =============================================================================
// PostgreSQL DDL Generator (for bidirectional editing)
// =============================================================================
export function generatePostgresSQL(schema: ParsedSchema): string {
  const lines: string[] = [];

  // Generate ENUMs first
  for (const [enumName, values] of schema.enums.entries()) {
    lines.push(`CREATE TYPE ${enumName} AS ENUM (${values.map(v => `'${v}'`).join(', ')});`);
    lines.push('');
  }

  // Generate tables
  for (const table of schema.tables) {
    lines.push(generateTableSQL(table));
    lines.push('');
  }

  return lines.join('\n').trim();
}

export function generateTableSQL(table: Table): string {
  const lines: string[] = [];
  const tableName = table.schema && !table.name.startsWith(table.schema + '.')
    ? `${table.schema}.${table.name}`
    : table.name;

  let createPrefix = 'CREATE';
  if (table.isTemporary) createPrefix += ' TEMPORARY';
  if (table.isUnlogged) createPrefix += ' UNLOGGED';

  lines.push(`${createPrefix} TABLE ${tableName} (`);

  const columnDefs: string[] = [];
  const constraints: string[] = [];

  for (const column of table.columns) {
    columnDefs.push(`  ${generateColumnSQL(column)}`);
  }

  // Add table-level constraints
  for (const check of table.checkConstraints) {
    constraints.push(`  CONSTRAINT ${check} CHECK (...)`);
  }

  const allDefs = [...columnDefs, ...constraints];
  lines.push(allDefs.join(',\n'));

  let closing = ')';
  if (table.inheritsFrom) {
    closing += ` INHERITS (${table.inheritsFrom})`;
  }
  if (table.isPartitioned && table.partitionType) {
    closing += ` PARTITION BY ${table.partitionType.toUpperCase()} (...)`;
  }
  closing += ';';

  lines.push(closing);

  return lines.join('\n');
}

function generateColumnSQL(column: Column): string {
  let def = `${column.name} ${column.type}`;

  if (column.isPrimaryKey) {
    def += ' PRIMARY KEY';
  }

  if (!column.nullable && !column.isPrimaryKey) {
    def += ' NOT NULL';
  }

  if (column.isUnique && !column.isPrimaryKey) {
    def += ' UNIQUE';
  }

  if (column.defaultValue) {
    def += ` DEFAULT ${column.defaultValue}`;
  }

  if (column.references) {
    def += ` REFERENCES ${column.references.table}(${column.references.column})`;
    if (column.references.onDelete) {
      def += ` ON DELETE ${column.references.onDelete}`;
    }
    if (column.references.onUpdate) {
      def += ` ON UPDATE ${column.references.onUpdate}`;
    }
  }

  return def;
}

// =============================================================================
// Prisma Schema Generator
// =============================================================================
export function generatePrismaSchema(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('// This is your Prisma schema file');
  lines.push('// Generated by Schema Weaver');
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql"');
  lines.push('  url      = env("DATABASE_URL")');
  lines.push('}');
  lines.push('');

  // Generate enums
  for (const [enumName, values] of schema.enums.entries()) {
    lines.push(`enum ${toPascalCase(enumName)} {`);
    for (const value of values) {
      lines.push(`  ${value}`);
    }
    lines.push('}');
    lines.push('');
  }

  // Generate models
  for (const table of schema.tables) {
    lines.push(generatePrismaModel(table, schema));
    lines.push('');
  }

  return lines.join('\n');
}

function generatePrismaModel(table: Table, schema: ParsedSchema): string {
  const lines: string[] = [];
  const modelName = toPascalCase(table.name);

  lines.push(`model ${modelName} {`);

  for (const column of table.columns) {
    lines.push(`  ${generatePrismaField(column, table, schema)}`);
  }

  // Add reverse relations
  const reverseRels = schema.relationships.filter(r => r.target.table === table.name);
  for (const rel of reverseRels) {
    const relModel = toPascalCase(rel.source.table);
    lines.push(`  ${toCamelCase(rel.source.table)}s ${relModel}[]`);
  }

  // Add @@map if table name differs from model name
  if (table.name !== modelName.toLowerCase()) {
    lines.push('');
    lines.push(`  @@map("${table.name}")`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generatePrismaField(column: Column, table: Table, schema: ParsedSchema): string {
  let prismaType = mapPostgresToPrisma(column.type, schema.enums);
  let modifiers: string[] = [];

  if (column.isPrimaryKey) {
    modifiers.push('@id');
    if (column.type.toLowerCase().includes('serial') || column.defaultValue?.includes('uuid')) {
      modifiers.push('@default(autoincrement())');
    }
    if (column.type.toLowerCase() === 'uuid') {
      modifiers.push('@default(uuid())');
    }
  }

  if (column.isUnique && !column.isPrimaryKey) {
    modifiers.push('@unique');
  }

  if (column.defaultValue) {
    const defaultVal = mapDefaultToPrisma(column.defaultValue);
    if (defaultVal) {
      modifiers.push(`@default(${defaultVal})`);
    }
  }

  if (column.references) {
    // This is a relation field
    const refModel = toPascalCase(column.references.table);
    lines.push(`  ${toCamelCase(column.references.table)} ${refModel}? @relation(fields: [${column.name}], references: [${column.references.column}])`);
  }

  let optional = column.nullable ? '?' : '';

  // Column name mapping if needed
  if (column.name.includes('_')) {
    const camelName = toCamelCase(column.name);
    if (camelName !== column.name) {
      modifiers.push(`@map("${column.name}")`);
    }
  }

  return `${column.name} ${prismaType}${optional} ${modifiers.join(' ')}`.trim();
}

function mapPostgresToPrisma(pgType: string, enums: Map<string, string[]>): string {
  const t = pgType.toLowerCase();

  // Check if it's an enum
  for (const enumName of enums.keys()) {
    if (t === enumName.toLowerCase()) {
      return toPascalCase(enumName);
    }
  }

  if (t.includes('serial') || t === 'integer' || t === 'int' || t === 'int4') return 'Int';
  if (t === 'bigint' || t === 'bigserial' || t === 'int8') return 'BigInt';
  if (t === 'smallint' || t === 'smallserial' || t === 'int2') return 'Int';
  if (t.includes('numeric') || t.includes('decimal')) return 'Decimal';
  if (t === 'real' || t === 'float4') return 'Float';
  if (t === 'double precision' || t === 'float8') return 'Float';
  if (t.includes('varchar') || t === 'text' || t.includes('char')) return 'String';
  if (t === 'boolean' || t === 'bool') return 'Boolean';
  if (t.includes('timestamp') || t === 'date') return 'DateTime';
  if (t === 'time') return 'DateTime';
  if (t === 'uuid') return 'String';
  if (t === 'json' || t === 'jsonb') return 'Json';
  if (t === 'bytea') return 'Bytes';
  if (t.endsWith('[]')) return mapPostgresToPrisma(t.slice(0, -2), enums) + '[]';

  return 'String';
}

function mapDefaultToPrisma(defaultValue: string): string | null {
  const d = defaultValue.toLowerCase();
  if (d.includes('now()') || d.includes('current_timestamp')) return 'now()';
  if (d === 'true') return 'true';
  if (d === 'false') return 'false';
  if (d.includes('gen_random_uuid') || d.includes('uuid_generate')) return 'uuid()';
  if (d.includes('autoincrement') || d.includes('nextval')) return 'autoincrement()';
  return null;
}

// =============================================================================
// Drizzle ORM Schema Generator
// =============================================================================
export function generateDrizzleSchema(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('// Drizzle ORM Schema');
  lines.push('// Generated by Schema Weaver');
  lines.push('');
  lines.push("import { pgTable, serial, text, varchar, integer, bigint, boolean, timestamp, uuid, json, jsonb, primaryKey, foreignKey, unique } from 'drizzle-orm/pg-core';");
  lines.push("import { relations } from 'drizzle-orm';");
  lines.push('');

  // Generate enums
  for (const [enumName, values] of schema.enums.entries()) {
    lines.push(`export const ${toCamelCase(enumName)} = ['${values.join("', '")}'] as const;`);
    lines.push(`export type ${toPascalCase(enumName)} = typeof ${toCamelCase(enumName)}[number];`);
    lines.push('');
  }

  // Generate tables
  for (const table of schema.tables) {
    lines.push(generateDrizzleTable(table));
    lines.push('');
  }

  // Generate relations
  for (const table of schema.tables) {
    const tableRels = schema.relationships.filter(r => r.source.table === table.name || r.target.table === table.name);
    if (tableRels.length > 0) {
      lines.push(generateDrizzleRelations(table, schema.relationships, schema.tables));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateDrizzleTable(table: Table): string {
  const lines: string[] = [];
  const varName = toCamelCase(table.name);

  lines.push(`export const ${varName} = pgTable('${table.name}', {`);

  for (const column of table.columns) {
    lines.push(`  ${generateDrizzleColumn(column)},`);
  }

  lines.push('});');
  return lines.join('\n');
}

function generateDrizzleColumn(column: Column): string {
  const t = column.type.toLowerCase();
  let drizzleType: string;
  let modifiers: string[] = [];

  // Map PostgreSQL type to Drizzle
  if (t.includes('serial')) {
    drizzleType = t === 'bigserial' ? `bigserial('${column.name}', { mode: 'number' })` : `serial('${column.name}')`;
  } else if (t === 'uuid') {
    drizzleType = `uuid('${column.name}')`;
  } else if (t.includes('varchar')) {
    const match = t.match(/varchar\((\d+)\)/);
    drizzleType = match ? `varchar('${column.name}', { length: ${match[1]} })` : `varchar('${column.name}')`;
  } else if (t === 'text') {
    drizzleType = `text('${column.name}')`;
  } else if (t === 'integer' || t === 'int' || t === 'int4') {
    drizzleType = `integer('${column.name}')`;
  } else if (t === 'bigint' || t === 'int8') {
    drizzleType = `bigint('${column.name}', { mode: 'number' })`;
  } else if (t === 'boolean' || t === 'bool') {
    drizzleType = `boolean('${column.name}')`;
  } else if (t.includes('timestamp')) {
    drizzleType = `timestamp('${column.name}')`;
  } else if (t === 'date') {
    drizzleType = `date('${column.name}')`;
  } else if (t === 'json') {
    drizzleType = `json('${column.name}')`;
  } else if (t === 'jsonb') {
    drizzleType = `jsonb('${column.name}')`;
  } else {
    drizzleType = `text('${column.name}')`; // fallback
  }

  if (column.isPrimaryKey) {
    modifiers.push('.primaryKey()');
  }
  if (!column.nullable && !column.isPrimaryKey) {
    modifiers.push('.notNull()');
  }
  if (column.isUnique && !column.isPrimaryKey) {
    modifiers.push('.unique()');
  }
  if (column.defaultValue) {
    const def = mapDefaultToDrizzle(column.defaultValue, t);
    if (def) modifiers.push(def);
  }

  return `${column.name}: ${drizzleType}${modifiers.join('')}`;
}

function mapDefaultToDrizzle(defaultValue: string, type: string): string | null {
  const d = defaultValue.toLowerCase();
  if (d.includes('now()') || d.includes('current_timestamp')) return '.defaultNow()';
  if (d.includes('gen_random_uuid') || d.includes('uuid_generate')) return ".default(sql`gen_random_uuid()`)";
  if (d === 'true') return '.default(true)';
  if (d === 'false') return '.default(false)';
  if (!isNaN(Number(defaultValue))) return `.default(${defaultValue})`;
  if (defaultValue.startsWith("'") && defaultValue.endsWith("'")) return `.default(${defaultValue})`;
  return null;
}

function generateDrizzleRelations(table: Table, relationships: Relationship[], tables: Table[]): string {
  const lines: string[] = [];
  const varName = toCamelCase(table.name);

  lines.push(`export const ${varName}Relations = relations(${varName}, ({ one, many }) => ({`);

  // Outgoing relations (this table has FK)
  const outgoing = relationships.filter(r => r.source.table === table.name);
  for (const rel of outgoing) {
    const refVar = toCamelCase(rel.target.table);
    lines.push(`  ${refVar}: one(${refVar}, {`);
    lines.push(`    fields: [${varName}.${rel.source.column}],`);
    lines.push(`    references: [${refVar}.${rel.target.column}],`);
    lines.push('  }),');
  }

  // Incoming relations (other tables reference this)
  const incoming = relationships.filter(r => r.target.table === table.name);
  for (const rel of incoming) {
    const refVar = toCamelCase(rel.source.table);
    lines.push(`  ${refVar}s: many(${refVar}),`);
  }

  lines.push('}));');
  return lines.join('\n');
}

// =============================================================================
// DBML Generator
// =============================================================================
export function generateDBML(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('// DBML Schema');
  lines.push('// Generated by Schema Weaver');
  lines.push('// View at dbdiagram.io');
  lines.push('');

  // Generate enums
  for (const [enumName, values] of schema.enums.entries()) {
    lines.push(`Enum ${enumName} {`);
    for (const value of values) {
      lines.push(`  ${value}`);
    }
    lines.push('}');
    lines.push('');
  }

  // Generate tables
  for (const table of schema.tables) {
    lines.push(generateDBMLTable(table));
    lines.push('');
  }

  // Generate refs (relationships)
  for (const rel of schema.relationships) {
    let refType = '>';  // many-to-one by default
    lines.push(`Ref: ${rel.source.table}.${rel.source.column} ${refType} ${rel.target.table}.${rel.target.column}`);
  }

  return lines.join('\n');
}

function generateDBMLTable(table: Table): string {
  const lines: string[] = [];

  lines.push(`Table ${table.name} {`);

  for (const column of table.columns) {
    let def = `  ${column.name} ${column.type}`;
    const settings: string[] = [];

    if (column.isPrimaryKey) settings.push('pk');
    if (!column.nullable) settings.push('not null');
    if (column.isUnique && !column.isPrimaryKey) settings.push('unique');
    if (column.defaultValue) settings.push(`default: ${column.defaultValue}`);
    if (column.references) {
      settings.push(`ref: > ${column.references.table}.${column.references.column}`);
    }

    if (settings.length > 0) {
      def += ` [${settings.join(', ')}]`;
    }

    lines.push(def);
  }

  lines.push('}');
  return lines.join('\n');
}

// =============================================================================
// Markdown Documentation Generator
// =============================================================================
export function generateMarkdownDocs(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('# Database Schema Documentation');
  lines.push('');
  lines.push('*Generated by Schema Weaver*');
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push(`- **Tables:** ${schema.tables.length}`);
  lines.push(`- **Relationships:** ${schema.relationships.length}`);
  lines.push(`- **Enums:** ${schema.enums.size}`);
  lines.push(`- **Views:** ${schema.views.length}`);
  lines.push(`- **Functions:** ${schema.functions.length}`);
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  lines.push('');
  for (const table of schema.tables) {
    lines.push(`- [${table.name}](#${table.name.toLowerCase()})`);
  }
  lines.push('');

  // Enums section
  if (schema.enums.size > 0) {
    lines.push('## Enums');
    lines.push('');
    for (const [enumName, values] of schema.enums.entries()) {
      lines.push(`### ${enumName}`);
      lines.push('');
      lines.push('| Value |');
      lines.push('|-------|');
      for (const value of values) {
        lines.push(`| \`${value}\` |`);
      }
      lines.push('');
    }
  }

  // Tables section
  lines.push('## Tables');
  lines.push('');

  for (const table of schema.tables) {
    lines.push(`### ${table.name}`);
    lines.push('');

    if (table.schema) lines.push(`**Schema:** ${table.schema}`);
    if (table.isPartitioned) lines.push(`**Partitioned:** Yes (${table.partitionType})`);
    if (table.isTemporary) lines.push(`**Temporary:** Yes`);
    if (table.inheritsFrom) lines.push(`**Inherits:** ${table.inheritsFrom}`);
    lines.push('');

    // Columns table
    lines.push('| Column | Type | Nullable | Key | Default |');
    lines.push('|--------|------|----------|-----|---------|');

    for (const column of table.columns) {
      const key = column.isPrimaryKey ? 'PK' : column.isForeignKey ? 'FK' : column.isUnique ? 'UQ' : '';
      const nullable = column.nullable ? 'Yes' : 'No';
      const defaultVal = column.defaultValue || '-';
      lines.push(`| \`${column.name}\` | \`${column.type}\` | ${nullable} | ${key} | ${defaultVal} |`);
    }
    lines.push('');

    // Foreign keys
    const fkColumns = table.columns.filter(c => c.references);
    if (fkColumns.length > 0) {
      lines.push('**Foreign Keys:**');
      lines.push('');
      for (const col of fkColumns) {
        let fkLine = `- \`${col.name}\` → \`${col.references!.table}.${col.references!.column}\``;
        if (col.references!.onDelete) fkLine += ` (ON DELETE ${col.references!.onDelete})`;
        lines.push(fkLine);
      }
      lines.push('');
    }
  }

  // Relationships diagram (text)
  lines.push('## Relationships');
  lines.push('');
  lines.push('```');
  lines.push('```');
  for (const rel of schema.relationships) {
    lines.push(`${rel.source.table}.${rel.source.column} ──> ${rel.target.table}.${rel.target.column}`);
  }
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// =============================================================================
// TypeScript Types Generator
// =============================================================================
export function generateTypeScriptTypes(schema: ParsedSchema): string {
  const lines: string[] = [];

  lines.push('// TypeScript Types');
  lines.push('// Generated by Schema Weaver');
  lines.push('');

  // Generate enum types
  for (const [enumName, values] of schema.enums.entries()) {
    lines.push(`export type ${toPascalCase(enumName)} = ${values.map(v => `'${v}'`).join(' | ')};`);
    lines.push('');
  }

  // Generate table interfaces
  for (const table of schema.tables) {
    lines.push(`export interface ${toPascalCase(table.name)} {`);
    for (const column of table.columns) {
      const tsType = mapPostgresToTypeScript(column.type, schema.enums);
      const optional = column.nullable ? '?' : '';
      lines.push(`  ${column.name}${optional}: ${tsType};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function mapPostgresToTypeScript(pgType: string, enums: Map<string, string[]>): string {
  const t = pgType.toLowerCase();

  // Check if it's an enum
  for (const enumName of enums.keys()) {
    if (t === enumName.toLowerCase()) {
      return toPascalCase(enumName);
    }
  }

  if (t.includes('int') || t.includes('serial') || t.includes('numeric') || t.includes('decimal') || t === 'real' || t.includes('float') || t.includes('double')) return 'number';
  if (t.includes('varchar') || t === 'text' || t.includes('char') || t === 'uuid') return 'string';
  if (t === 'boolean' || t === 'bool') return 'boolean';
  if (t.includes('timestamp') || t === 'date' || t === 'time') return 'Date';
  if (t === 'json' || t === 'jsonb') return 'Record<string, unknown>';
  if (t === 'bytea') return 'Buffer';
  if (t.endsWith('[]')) return mapPostgresToTypeScript(t.slice(0, -2), enums) + '[]';

  return 'unknown';
}

// =============================================================================
// Helpers
// =============================================================================
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

function toCamelCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toLowerCase());
}

// Fix the standalone lines reference issue in generatePrismaField
const lines: string[] = [];
