import { ParsedSchema, EnumType } from '@/lib/sql-parser/types/core-types';
import { parsePostgresSQL } from '@/lib/sql-parser';
import { schemaToSql } from '@/lib/schema-utils';

export interface SplitSqlResult {
    fileName: string;
    content: string;
    folderPath?: string[]; // e.g. ['public'] or ['public', 'tables']
    isFolder?: boolean;
}

function createEmptySchema(): ParsedSchema {
    return {
        tables: [],
        relationships: [],
        enums: new Map(),
        enumTypes: [],
        views: [],
        triggers: [],
        indexes: [],
        sequences: [],
        functions: [],
        policies: [],
        extensions: [],
        schemas: [],
        domains: [],
        compositeTypes: [],
        roles: [],
        stats: {
            dataTypes: new Map(),
            primaryKeys: 0,
            foreignKeys: 0,
            uniqueConstraints: 0,
            checkConstraints: 0,
            notNullConstraints: 0,
            indexTypes: new Map(),
            generatedColumns: 0,
            defaultValues: 0,
            partitionedTables: 0,
            childPartitions: 0,
            temporaryTables: 0,
            inheritedTables: 0,
            rlsPolicies: 0,
        },
        errors: [],
        warnings: [],
        confidence: 1,
    };
}

/**
 * Takes a raw SQL string from the database and splits it based on the user's requested mode.
 */
export function splitPulledSql(sql: string, mode: 'single' | 'split-by-schema' | 'split-by-table'): SplitSqlResult[] {
    if (mode === 'single') {
        return [{ fileName: 'schema.sql', content: sql }];
    }

    try {
        const schema = parsePostgresSQL(sql);
        const results: SplitSqlResult[] = [];

        if (mode === 'split-by-schema') {
            // Group objects by schema namespace
            const schemas = new Set<string>();
            schema.tables.forEach(t => schemas.add(t.schema || 'public'));
            schema.enumTypes?.forEach(e => schemas.add(e.schema || 'public'));

            for (const schemaName of schemas) {
                // Filter schema object to only contain this schema's items
                const filteredSchema: ParsedSchema = {
                    ...createEmptySchema(),
                    tables: schema.tables.filter(t => (t.schema || 'public') === schemaName),
                    enumTypes: schema.enumTypes?.filter(e => (e.schema || 'public') === schemaName) || [],
                };

                // Add the header comment manually to individual files too
                const header = `/*\n * Schema: ${schemaName}\n * Auto-generated by Schema Weaver\n */\n\n`;
                // Populate enums array so schemaToSql can read it (it reads .enums, not .enumTypes)
                (filteredSchema as any).enums = filteredSchema.enumTypes;
                const content = header + schemaToSql(filteredSchema as any);

                results.push({
                    fileName: `${schemaName}.sql`,
                    content,
                    folderPath: [],
                    isFolder: false,
                });
            }
        } else if (mode === 'split-by-table') {
            // Group by Schema Folder -> Table File
            const schemas = new Set<string>();
            schema.tables.forEach(t => schemas.add(t.schema || 'public'));
            schema.enumTypes?.forEach(e => schemas.add(e.schema || 'public'));

            for (const schemaName of schemas) {
                // Add a folder for the schema (handled by recursive folder creation logic usually, but let's be explicit)
                results.push({
                    fileName: schemaName,
                    content: '',
                    folderPath: [],
                    isFolder: true,
                });

                // Add tables inside this schema folder
                const tables = schema.tables.filter(t => (t.schema || 'public') === schemaName);
                for (const table of tables) {
                    const singleTableSchema: ParsedSchema = { ...createEmptySchema(), tables: [table] };
                    (singleTableSchema as any).enums = singleTableSchema.enumTypes;
                    const content = schemaToSql(singleTableSchema as any);
                    results.push({
                        fileName: `${table.name}.sql`,
                        content,
                        folderPath: [schemaName],
                    });
                }

                // Add enums inside this schema folder (bundled into an enums.sql if they exist)
                const enums = schema.enumTypes?.filter(e => (e.schema || 'public') === schemaName) || [];
                if (enums.length > 0) {
                    const singleEnumSchema: ParsedSchema = { ...createEmptySchema(), enumTypes: enums };
                    (singleEnumSchema as any).enums = singleEnumSchema.enumTypes;
                    const content = schemaToSql(singleEnumSchema as any);
                    results.push({
                        fileName: `enums.sql`,
                        content,
                        folderPath: [schemaName],
                    });
                }
            }
        }

        return results;
    } catch (e) {
        console.error('Failed to parse and split SQL, falling back to single file', e);
        return [{ fileName: 'schema.sql', content: sql }];
    }
}
